# Generated by Django 4.0.5 on 2022-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Proyekt nomi', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Proyekt tavsifi')),
                ('link', models.URLField(default=None, help_text='Githubdagi linki', null=True)),
            ],
        ),
    ]
