# Generated by Django 4.0.5 on 2022-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Xabar yuboruvchining ismi', max_length=200)),
                ('sender_email', models.EmailField(help_text='Xabar yuboruvchining email manzili', max_length=200)),
                ('subject', models.CharField(help_text='Xabar mavzusi', max_length=200)),
                ('text', models.TextField(help_text='Xabar matni')),
            ],
        ),
    ]
